CREATE TABLE IF NOT EXISTS pref(
    id           INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    pref_id INTEGER
);

CREATE TABLE IF NOT EXISTS line(
    id           INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    linecd INTEGER
);

CREATE TABLE IF NOT EXISTS stationcd(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  stationcd INTEGER
);

CREATE TABLE IF NOT EXISTS stationg(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  stationgcode INTEGER
);


CREATE TABLE IF NOT EXISTS line(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  linecd INTEGER
);

